---
name: Aruba DDNS
slug: aruba_ddns
description: Aggiorna record DNS Aruba verso IP pubblico e rinnova certificati Let's Encrypt
version: 0.2.3
url: https://github.com/Cobracco/home-assistant-aruba-ddns/tree/main/aruba-ddns
startup: services
init: false
map:
  - ssl:rw
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
options:
  api_base: https://api.arubabusiness.it
  api_key: null
  username: null
  password: null
  otp: ""
  seconds: 300
  ipv4: ""
  ipv6: ""
  records:
    - zone: example.it
      name: "@"
      type: A
      create_if_missing: true
      content: ""
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
    domains: []
    zones: []
    propagation_seconds: 120
schema:
  api_base: str
  api_key: str
  username: str
  password: password
  otp: str?
  seconds: int(60,86400)
  ipv4: str?
  ipv6: str?
  records:
    - zone: str
      name: str
      type: list(A|AAAA)
      create_if_missing: bool?
      content: str?
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
    domains:
      - str
    zones:
      - str
    propagation_seconds: int(10,1200)
